openapi: 3.0.1

info:
  title: OpenAPI Specification Tests
  version: 1.0.0

paths: 
    /external-param:
      get:
        description: Uses a parameter defined in another file.
        parameters:
          - $ref: 'https://raw.githubusercontent.com/guizoxxv/open-api-example/main/reusableParam.yaml'
        responses:
          200:
            description: OK
    /external-param-combined:
      get:
        description: Uses a parameter defined in another file and combines with local parameters.
        parameters:
          - name: reusableParam
            allOf:
              - $ref: 'https://raw.githubusercontent.com/guizoxxv/open-api-example/main/reusableParam.yaml'
              - required: true
              - schema:
                type: number
                default: 50
        responses:
          200:
            description: OK           
    /external-responses-combined:
      get:
        description: Uses multiple responses defined in another file and combines with local responses.
        responses:
          allOf:
            - $ref: '#/components/responses/GeneralResponses'
            - 200:
                description: OK

components:
  responses:
    GeneralResponses:
      $ref: https://raw.githubusercontent.com/guizoxxv/open-api-example/main/generalResponses.yaml
